[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "forecast_sticker_sales"
version = "0.1.0"
dependencies = [
    "loguru>=0.7.3",
    "pandas>=2.2.3",
]
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
    "pytest",
    "notebook"
]
